const modalTypes = {
  CART_MODAL_OPEN: 'CART_MODAL_OPEN',
  CART_MODAL_CLOSE: 'CART_MODAL_CLOSE',
  MENU_MODAL_OPEN: 'MENU_MODAL_OPEN',
  MENU_MODAL_CLOSE: 'MENU_MODALCLOSE',
}

export default modalTypes;